version: 2
updates:
  # basic application
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # npm in webgui
  - package-ecosystem: "npm"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/web_gui_seed"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  # cargo in webgui
  - package-ecosystem: "cargo"
    directory: "/web_gui_seed"
    schedule:
      interval: "weekly"
