[package]
name = "viola"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[dependencies]
app_dirs = "1.2"         # Put your app's data in the right place on every platform
clap = "2.31"                    # A simple to use, efficient, and full featured  Command Line Argument Parser 
diesel = { version = "1.3", features = ["sqlite", "r2d2"] }
error-chain = "0.11"
indicatif = "0.9"    # A progress bar and cli reporting library for Rust
taglib = {git = "https://github.com/ebassi/taglib-rust.git", rev="513dabf"}        # Rust bindings for TagLib   
gdk = "0.8"               # Rust bindings for the GDK 3 library
gdk-pixbuf = "0.4"        # Rust bindings for the GdkPixbuf library 
gio = "0.4"             # Rust bindings for the Gio library    
gstreamer = "0.11"               # Rust bindings for GStreamer     
preferences = "1.1"         # Read and write user-specific application data (in stable Rust)
rayon = "1.0"               # Simple work-stealing parallelism for Rust   
serde_derive = "1.0"                   # Macros 1.1 implementation of #[derive(Serialize, Deserialize)]
serde = "1.0"                      # A generic serialization/deserialization framework
open = "1.2"
toml = "0.4"
walkdir = "2"


[dependencies.gtk]
version = "0.4.0"
features = ["v3_12"]
