[package]
name = "viola"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[dependencies]
error-chain = "0.11"
taglib = {git = "https://github.com/ebassi/taglib-rust.git", rev="513dabf"}        # Rust bindings for TagLib    
gstreamer = "0.10.2"               # Rust bindings for GStreamer      
walkdir = "2"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]