[package]
name = "viola"
version = "0.2.1"
license = "GPL-3.0-only"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
clap = "2.33.3"
diesel = { version = "1.4.7", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["sqlite"] }
erased-serde = "0.3.16"
error-chain = "0.12.4"
futures = "0.3.16"
log = { version = "0.4.14", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "0.9.0"
indicatif = { version = "0.16.2", features = ["rayon"] }
image = "0.23.14"
humantime = "2.1.0"
#jwalk = "0.4"    # A progress bar and cli reporting library for Rust
taglib = "1.0.0"
gstreamer = "0.17.2"
glib = "0.14.2"
percent-encoding = "2.1.0"
preferences = "1.1.0"
rayon = "1.5.1"
serde_derive = "1.0.127"
serde_json = "1.0.66"
serde = "1.0.128"
open = "2.0.0"
rand = "0.8.4"
rusqlite = "0.25.3"
toml = "0.5.8"
owning_ref = "0.4.1"
walkdir = "2.3.2"
web-view = "0.7.3"
viola_common = {path ="viola_common", features =["backend"]}
itertools = "0.10.1"
zbus = "1.9.1"
bus = "2.2.3"
parking_lot = { version = "0.11.1", features = ["serde", "deadlock_detection"] }
warp = "0.3.1"
tokio = "1.9.0"
directories = "3.0.2"
anyhow = "1.0.42"
