[package]
name = "viola"
version = "0.4.1"
license = "GPL-3.0-only"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = { version = "4.3.10", features = ["cargo", "derive"] }
diesel = { version = "2.1.0", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.1.0", features = ["sqlite"] }
futures = "0.3.28"
log = { version = "0.4.19", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "0.10.0"
indicatif = { version = "0.17.5", features = ["rayon"] }
humantime = "2.1.0"
taglib = "1.0.0"
gstreamer = "0.20.6"
percent-encoding = "2.3.0"
preferences = "1.1.0"
rayon = "1.7.0"
serde_json = "1.0.99"
serde = { version = "1.0.164", features = ["derive"] }
open = "5.0.0"
rand = "0.8.5"
toml = "0.7.5"
walkdir = "2.3.3"
viola_common = {path ="viola_common", features =["backend"]}
itertools = "0.11.0"
zbus = "3.14.1"
parking_lot = { version = "0.12.1", features = ["serde", "deadlock_detection"] }
warp = { version = "0.3.5", features = ["compression"] }
tokio = { version = "1.29.1", features = ["full"] }
directories = "5.0.1"
anyhow = "1.0.71"
