[package]
name = "viola"
version = "0.4.0"
license = "GPL-3.0-only"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]
edition = "2018"

[dependencies]
base64 = "0.21.0"
clap = { version = "4.1.4", features = ["cargo", "derive"] }
diesel = { version = "2.0.3", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.0.0", features = ["sqlite"] }
futures = "0.3.26"
log = { version = "0.4.17", features = ["max_level_debug", "release_max_level_warn"] }
env_logger = "0.10.0"
indicatif = { version = "0.17.3", features = ["rayon"] }
humantime = "2.1.0"
taglib = "1.0.0"
gstreamer = "0.19.7"
glib = "0.16.7"
percent-encoding = "2.2.0"
preferences = "1.1.0"
rayon = "1.6.1"
serde_derive = "1.0.152"
serde_json = "1.0.92"
serde = "1.0.152"
open = "3.2.0"
rand = "0.8.5"
toml = "0.7.2"
walkdir = "2.3.2"
viola_common = {path ="viola_common", features =["backend"]}
itertools = "0.10.5"
zbus = "3.9.0"
parking_lot = { version = "0.12.1", features = ["serde", "deadlock_detection"] }
warp = { version = "0.3.3", features = ["compression"] }
tokio = { version = "1.25.0", features = ["full"] }
directories = "4.0.1"
anyhow = "1.0.69"
zvariant = "3.10.0"
webkit2gtk = "0.18.2"
gtk = "0.15.5"
