[package]
name = "viola"
version = "0.1.0"
authors = ["Narfinger <Narfinger@users.noreply.github.com>"]

[dependencies]
taglib = {git = "https://github.com/ebassi/taglib-rust.git", rev="513dabf"}        # Rust bindings for TagLib    
walkdir = "2"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]