[tasks.build_debug_backend]
command = "cargo"
args = ["build"]

[tasks.build_debug_frontend]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = ["--version"]}
cwd = "web_gui_seed/"
command = "trunk"
args = ["build"]


[tasks.build_backend]
command = "cargo"
args = ["build", "--release"]

[tasks.build_frontend]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = ["--version"]}
cwd = "web_gui_seed/"
command = "trunk"
args = ["build", "--release"]


[tasks.build]
dependencies = ["build_backend", "build_frontend"]

[tasks.ci-flow]
# CI task will run cargo build but do not run tests for the moment
dependencies = [
    "pre-build",
    "build-verbose",
    "post-build",
]
