[package]
name = "web_gui_yew"
version = "0.1.0"
edition = "2021"

[profile.release]
# panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
console_error_panic_hook = "0.1.7"
futures = "0.3.28"
humantime = "2.1.0"
indextree = "4.6.0"
log = "0.4.19"
reqwasm = "0.5.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
viola_common = { path = "../viola_common" }
wasm-bindgen = "0.2.86"
wasm-bindgen-futures = "0.4.36"
wasm-logger = "0.2.0"
web-sys = "0.3.63"
yew = { version = "0.20.0", features = ["csr"] }

