[package]
name = "web_gui_yew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
futures = "0.3.21"
gloo-net = "0.2.0"
humantime = "2.1.0"
log = "0.4.16"
reqwasm = "0.5.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
viola_common = { path = "../viola_common" }
wasm-bindgen-futures = "0.4.30"
wasm-logger = "0.2.0"
wee_alloc = "0.4.5"
yew = "0.19.3"

