[package]
name = "web_gui_yew"
version = "1.1.0"
edition = "2021"

[profile.release]
# panic = 'abort'
codegen-units = 1
opt-level = 'z'
lto = true

[dependencies]
console_error_panic_hook = "0.1.7"
futures = "0.3.29"
humantime = "2.1.0"
indextree = "4.6.0"
log = "0.4.20"
reqwasm = "0.5.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
viola_common = { path = "../viola_common" }
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4.37"
wasm-logger = "0.2.0"
web-sys = "0.3.65"
yew = { version = "0.21.0", features = ["csr"] }

