version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: cargo build
    test:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: cargo test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
