version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
            - run: cargo build
    test:
        docker:
            - image: circleci/rust:latest
        steps:
            - checkout
            - run: cargo test
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test
