[package]
name = "viola_common"
version = "0.1.0"
authors = ["Narfinger <narfinger@noreply.github.com>"]
edition = "2018"

[features]
backend = ["diesel"]

[dependencies]
diesel = { version = "1.4.8", features = ["sqlite"], optional = true }
serde_json = "1.0.72"
serde = { version = "1.0.130", features = ["derive"] }
