[package]
name = "viola_common"
version = "0.1.0"
authors = ["Narfinger <narfinger@noreply.github.com>"]
edition = "2018"

[features]
backend = ["diesel"]

[dependencies]
diesel = { version = "1.4.7", features = ["sqlite"], optional = true }
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
