[package]
name = "viola_common"
version = "0.5.0"
authors = ["Narfinger <narfinger@noreply.github.com>"]
edition = "2018"

[features]
backend = ["diesel"]

[dependencies]
diesel = { version = "2.0.4", features = ["sqlite"], optional = true }
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
