[package]
name = "viola_common"
version = "0.1.0"
authors = ["Narfinger <narfinger@noreply.github.com>"]
edition = "2018"

[features]
backend = ["diesel", "actix", "actix_derive"]

[dependencies]
actix = { version = "0.10", default-features = false, optional = true }
actix_derive = {version ="0.5", optional = true}
diesel = { version = "1.4", features = ["sqlite"], optional=true}
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
