name: CI
on: [push]
jobs:
  build_rust:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt install libgstreamer1.0-dev gnome-devel
      - run: cargo build --release --all-features
  build_web:
    name: Build NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
        working-directory: "web_gui"
      - run: npm run build
        working-directory: "web_gui"