on: [push]

name: CI
jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt install libgstreamer1.0-dev libpango1.0-dev libatk1.0-dev libsoup-gnome2.4-dev libgdk3.0-cil-dev
      - run: cargo build --release --all-features
