name: CI
on: [push]
jobs:
  build_rust:
    name: "Rust Project"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install gnome-devel libsoup2.4-dev libtag1-dev libtagc0-dev libwebkit2gtk-4.0-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
      - run: cargo build
  build_web:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: "NPM Install"
        working-directory: "web_gui_yew"
        run: npm install
      - run: trunk build
        working-directory: "web_gui_yew"
