name: CI
on: [push]
jobs:
  build_rust:
    name: "Rust Project"
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install libgstreamer1.0-dev gnome-devel libsoup2.4-dev libtag1-dev libtagc0-dev libwebkit2gtk-4.0-dev
      - run: cargo build
  build_web:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: "NPM Install"
        working-directory: "web_gui_yew"
        run: npm install
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install -f wasm-bindgen-cli trunk
      - run: trunk build
        working-directory: "web_gui_yew"
