name: CI
on: [push]
jobs:
  build_rust:
    name: "Rust Project"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v1
      - run: sudo apt update
      - run: sudo apt install libgstreamer1.0-dev gnome-devel libsoup2.4-dev libwebkit2gtk-4.0-dev libtag1-dev libtagc0-dev npm
      - run: cd web_gui_seed/
      - run: npm install
      - run: cd ../
      - run: cargo make ci-flow
